# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gladys Project
description: > # this means to ignore newlines until "baseurl:"
    Your home assistant based on a Raspberry Pi
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gladysproject.com" # the base hostname & protocol for your site, e.g. http://example.com

## I18N
languages: ["en", "fr"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  fr: Fran√ßais
  en: English

# Social network
twitter_username: gladysproject
github_username:  gladysproject
facebook_username: gladysproject
instagram_username: gladysproject
plugins: [jekyll-feed, jekyll-paginate-v2, jekyll-seo-tag, jekyll-sitemap]

# Tracking
google_analytics: UA-42837031-1
sumo-site-id: d1640d1e25d422b2dececeb749db8ca19998f2a44e94b8b2bceaa9e216c26dad

#SEO plugins infos
twitter:
  username: gladysproject
logo: /assets/images/presentation/facebook_share_gladys.png
social:
  name: Gladys Project
  links:
    - https://twitter.com/gladysproject
    - https://www.facebook.com/gladysproject
    - https://www.instagram.com/gladysproject
    - https://github.com/gladysproject

# Build settings
markdown: kramdown
theme: minima

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num"
  sort_field: 'date'
  sort_reverse: true

mailchimp:
  fr: 
    url: //gladysproject.us10.list-manage.com/subscribe/post?u=2987d27cbb489c6da217450c2&amp;id=e20efa438f
    key: b_2987d27cbb489c6da217450c2_e20efa438f
  en:
    url: //gladysproject.us10.list-manage.com/subscribe/post?u=2987d27cbb489c6da217450c2&amp;id=4c1084579b
    key: b_2987d27cbb489c6da217450c2_e20efa438f

disqus:
    shortname: gladys-project

comments:
  disqus:
    short_name: gladys-project
    api_key: RYpR6fAgb4bkw4Ia5WvrBCkD5ROwxC4J6v8I5n1Hb1kWrjZNNiRaQ5XJHPASzYib

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
